service: serverless-demo # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 30
  stage: dev
  region: us-east-1

functions:
  user:
    handler: user.handler
    events:
      - http:
          path: getUsers
          method: get
          cors: true
      - http:
          path: addUser
          method: post
          cors: true
      - http:
          path: deleteUser
          method: post
          cors: true
      - http:
          path: updateUser
          method: post
          cors: true

plugins:
- serverless-offline
